### ISSUE TITLE
Text Based Commands

### ISSUE THREAD

**Issue by yepidoodles** [DragonTechMC/DTCommands#7]
Configurable commands which do not contain links, just text (multiple lines, pagination?)

**Comment by linkinkov** [comment]
How about command like:
!text what mean /g text ?
Will be great to make like Essentials chat global chat

**Comment by yepidoodles** [comment]
Do you mean like a text channel?

**Comment by linkinkov** [comment]
yeah

**Comment by yepidoodles** [comment]
I have another project going for text channels

**Comment by linkinkov** [comment]
open source? Let me see it

**Comment by yepidoodles** [comment]
https://github.com/DragonTechMC/DTChannels

It's the first project I'm doing alone, so it's taking a long time, especially as I also run 3 servers.

**Comment by linkinkov** [comment]
Its will have local and global chat fuction?

**Comment by yepidoodles** [comment]
No, but I can consider adding it.

**Comment by linkinkov** [comment]
Will be great, if its possible
